### ISSUE TITLE
启用插件500

### ISSUE THREAD

**Issue by Seevil** [mikeyzm/Light-AudioPlayer#1]
非常纠结=_=||

**Comment by mikeyzm** [comment]
插件文件夹名字必须为LightAudioPlayer

**Comment by mikeyzm** [comment]
插件最新版已经规定了文件夹名称，[另外关于插件的issue交到这里吧](https://github.com/mikeyzm/Light-AudioPlayer-Plugin/issues)

**Comment by Seevil** [comment]
哦，谢谢撒~

**Comment by mikeyzm** [comment]
:smile:

**Comment by mikeyzm** [comment]
:wink: 不谢
